### ISSUE TITLE
Specific Env seeds run in common env

### ISSUE THREAD

**Issue by sonmaximum** [kristijorgji/goseeder#5]
https://github.com/kristijorgji/goseeder/blob/cfffdf1d1ce419cf23774b025ef425b385aa5f9e/seeder.go#L128

On the line referenced, the  `c.env == ""` condition is true for all seeders in the common env, so all seeders get run, that is, including ones that are registered for specific environments.

When I run `go run main.go --gseed`, I see 
```
Running all seeders...

[categoriesSeeder] started seeding...
[categoriesSeeder] seeded successfully, duration 9.838459ms

[testCategoriesSeeder] started seeding...
[testCategoriesSeeder] seeded successfully, duration 55.890833ms
```

This seems contrary to the idea that those seeds are registered to only run in the specified environments.

It seems like the `c.env == ""` should be removed ( as you really need both c.env and seeder.env to be "", which is covered by the following `c.env == seeder.env`)

Or am I misunderstanding something?

Aside, the `c.skipCommon == false` at the end of the line could just be `!c.skipCommon`, right?

**Comment by sonmaximum** [comment]
Opened a PR just in case

**Comment by kristijorgji** [comment]
Sorry for super late reply, I just had the notification email from github in spam of my email! and saw it just now.


Thanks for the PR and report here. 

The idea of common seeds is that "common" is special environment that runs everytime for all environments.

For example, you might want to setup `OrderStates` open payed etc for all environments, that can be a common seed so you don't copy paste in all envs.

That is the idea and user can use the commons only if they need it, but yes they run always at the moment

**Comment by kristijorgji** [comment]
To skip common seeds use

```
  -gs-skip-common
        goseeder - this arg has effect only if also gsenv if set, then will not run the common seeds (seeds that do not have any env specified)
```

or programmatically example
```
err := goseeder.Execute(con, goseeder.ForEnv("test"), goseeder.ShouldSkipCommon(true))
```

Both are documented in the readme.
Closing for now, if I misunderstood something re-open and add more details. Thanks

**Comment by kristijorgji** [comment]
Added also this point into README so everyone can understand easier the purpose and functionality of `common` special env

https://github.com/kristijorgji/goseeder#a-note-on-common-seeds
